const amqp = require('amqplib');
const dotenv = require('dotenv');
dotenv.config();

amqp.connect(process.env.AMQP_CONN) 
.then((connection)=>{
    connection.createChannel()
    .then((channel)=>{
        var queue = 'task_queue';
      channel.assertQueue(queue);
      channel.consume(queue,(message)=>{
          console.log(`The Received, Autogenerated Registered ID is : ${message.content}`);
      },{noAck:true}) 
    })
    .catch((error)=>{
        console.log(error);
    })
})
.catch((error)=>{
    console.log(error);
})

